version: "3.3"

services:
  prometheus:
    image: prom/prometheus
    network_mode: host
    volumes:
      - /mnt/prometheus_conf:/etc/prometheus
      - /mnt/prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped


  alertmanager:
    image: prom/alertmanager
    volumes:
      - /mnt/alertmanager_conf:/etc/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    network_mode: host
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana
    network_mode: host
    restart: unless-stopped
    
  node-exporter:
    image: prom/node-exporter:v1.1.2
    ports:
      - 9100:9100
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
